### ISSUE TITLE
User Persona

### ISSUE THREAD

**Issue by TrisRuhm** [LLM-TTT/project#10]

**Comment by tc020** [comment]
[User Persona.pdf](https://github.com/LLM-TTT/project/files/13187858/User.Persona.pdf)

**Comment by tm114** [comment]
[User Personas.pdf](https://github.com/LLM-TTT/project/files/13189093/User.Personas.pdf)

**Comment by tc020** [comment]
Habe die vorgeschlagenen User Personas ausgearbeitet und in eine PDF gepackt. Pro Seite eine User Persona.
[All User Persona Complete.pdf](https://github.com/LLM-TTT/project/files/13195585/All.User.Persona.Complete.pdf)

**Comment by tc020** [comment]
@tm114 Wir haben uns dazu entschieden in der Präsentation den Dr. Wagner zu verwenden. Kannst du für den bitte im nachfolgenden Link eine User Persona anlegen? 

https://www.hubspot.com/make-my-persona

**Comment by tm114** [comment]
Hoffe das passt so

![Image](https://github.com/LLM-TTT/project/assets/137153514/18868e54-d79b-41da-8271-aaed677c0d94)

**Comment by tc020** [comment]
@tm114 Noch zwei Änderungen: Bei Biggest Challenges ist ein Copy&Paste Fehler passiert und die Liste wurde doppelt reinkopiert. 

Am besten mach folgende Liste bitte daraus: 
* Wohlmöglich bereits bestehende Patente finden können
* Auskunft über Patentanfragen schnell und effektiv anbieten können
* Zwiespalt zwischen Kommerzialisierung und Forschung
* Stress mit Terminen und Fristen 

Bei der Liste "Reports to" am besten noch "**Forschungsabteilung**" hinzufügen.

Und generell würde ich LLM-TTT überall rausschmeißen, weil unsere Anwendung kommt ja erst noch. Das soll den Status darstellen, bevor unsere Anwendung kommt.

Also bei "Tools they need to do their job" bitte LLM-TTT Anwendung durch "**Kaffe, Zeit & Konzentration**" ersetzen und an 2. Stelle packen. Ist aber mehr so ein Fun-Ding. Falls du das für unnötig hältst, dann gern auch ganz weglassen. 😄 

Bei "They gain Information By" den Satz ganz ersetzen durch: "**Intensive Recherche in verschiedenen Datenbanken auf Basis verschiedener Schlüsselwörter und Klassifikationen**"

Danke dir 😘
