### ISSUE TITLE
Promptauswertung Klassifikation

### ISSUE THREAD

**Issue by TrisRuhm** [LLM-TTT/project#26]

**Comment by tc020** [comment]
[Google Doc Outputs](https://onedrive.live.com/edit.aspx?resid=8D350AA67FCD5BEC!7394&ithint=file%2cxlsx&nav=MTVfezVENTc5QUE5LUY4NjMtNEMwOC04OUVDLTkwNEVERjgzRUMzNH0&wdo=2&authkey=!AEzgfB9ORJhdqAA)

ToDo IPC Ergebnisse überprüfen + ein weiteres Patentbeispiel (Abstract, etc)

**Comment by tc020** [comment]
Überprüfung der IPC Ergebnisse:

✔ 1. G06K 9/00 - Recognition of data; recognition of biometric data (e.g., fingerprint, face)  
✔ 2. G07C 9/00 - Individual entry or exit registers (e.g., for vehicles)
✔ 3. B60R 25/00 - Fittings or systems for preventing or indicating unauthorized use or theft of vehicles (e.g., biometric vehicle access) 
✔ 4. G06F 21/32 - Access control; Network architectures or network communication protocols for network security for controlling access to resources of the network, e.g., using keys or access control lists
✔ 5. G06F 21/62 - Protecting access to data via a platform, e.g., using keys or access control rules to features or functions of an application
✔ 6. H04L 29/06 - Network architectures or network communication protocols for network security (e.g., involving user or device authentication)
☑  7. B60R 25/10 - Means to switch the anti-theft system on or off using electronic identifiers containing a code not memorised by the user
✔ 8. B60R 25/24 - Means to switch the anti-theft system on or off using biometric characteristics of the user, e.g. fingerprints, voice patterns

☑ = Erklärung von OpenAI weicht schon ziemlich ab. Man könnte es aber großzügig noch als "erfüllt" betrachten

Quelle: https://depatisnet.dpma.de/ipc/ipc.do

**Comment by tc020** [comment]
Überprüfung der USPTO Ergebnisse:

**1. Biometric Vehicle Access System technology:**
   - Class: 340 (Communications: Electrical) ✔
   - Subclass: 5.9 (Biometrics) ❌ => 5.82

**2. Advanced biometric authentication in vehicles:**
   - Class: 340 (Communications: Electrical) ✔
   - Subclass: 5.92 (Biometrics) ❌ => 5.82

**3. Biometric sensors in door handles and ignition systems:**
   - Class: 340 (Communications: Electrical) ✔
   - Subclass: 5.9 (Biometrics) ❌ => 5.82
   - Subclass: 5.91 (Access Control) ❌ => ???

**4. Vehicle security with biometric verification process:**
   - Class: 340 (Communications: Electrical) ✔
   - Subclass: 5.9 (Biometrics) ❌ => 5.82
   - Subclass: 5.91 (Access Control) ❌ => ???

**5. Anti-spoofing measures in biometric vehicle access:**
   - Class: 340 (Communications: Electrical) ✔
   - Subclass: 5.9 (Biometrics) ❌ => 5.82
   - Subclass: 5.92 (Anti-spoofing) ❌ => 568.1 Anti-theft?


❌ = Nicht gefunden, alternativ nach ähnlichen Subkategorien gesucht.

Quellen: https://www.uspto.gov/web/patents/classification/uspcindex/indextouspc.htm
https://www.uspto.gov/sites/default/files/documents/caau.pdf
