### ISSUE TITLE
Kriterienkatalog für Auswertung von Patenten

### ISSUE THREAD

**Issue by TrisRuhm** [LLM-TTT/project#31]

**Comment by tc020** [comment]
* Patent-Nummer (zB DE328932893829); Um Dubletten auszuschließen
* Abstract unterteilen in 10 Key Words und diese mit den Key Words aus zu Beginn abgleichen. In 10er Schritten prozentual angeben, wie sehr sich diese decken. Wenn zB nur 7 Key Words übereinstimmen, dann passt das Ergebnis zu 70%.
* **Bonus:** Vergleichen ob die jeweilig angegebene Classification im Patent mit einer der Classifications von uns übereinstimmt.
