### ISSUE TITLE
prompts für Auswertung der Patente

### ISSUE THREAD

**Issue by TrisRuhm** [LLM-TTT/project#32]

**Comment by tc020** [comment]
"Teile das Abstract in 10 Schlüsselwörter auf und gleiche diese mit den zu Beginn gegebenen Schlüsselwörtern ab. Gib in 10er Schritten prozentual an, wie gut sich die beiden Sets decken. Beispiel: Wenn 7 Schlüsselwörter übereinstimmen, ist das Ergebnis zu 70% deckend.."

**Comment by tm114** [comment]
Ich hätte noch einen Vorschlag, die Ähnlichkeiten vielleicht etwas genauer bestimmen zu können. Ich habe von zwei zuvor generierten Geschichten die Ähnlichkeit bestimmen lassen und darum gebeten, diese in Prozent anzugeben. Das hat GPT-3.5 gemacht und eine wie ich finde Vernünftige Prozentzahl genannt.
Gestern hatten wir ja auch kurz angesprochen, dass es eventuell etwas grob sein könnte, zwei Patente auf nur 10 Wörter zu reduzieren und die Matches zu zählen. Ein Vergleich der vollständigen Abstracts wäre da vielleicht erfolgreicher.
[Kindergeschichte Ähnlichkeit.txt](https://github.com/LLM-TTT/project/files/13646045/Kindergeschichte.Ahnlichkeit.txt)
