### ISSUE TITLE
Datenbanken recherchieren

### ISSUE THREAD

**Issue by TrisRuhm** [LLM-TTT/project#6]

**Comment by tc020** [comment]
Liste Datenbanken die für uns in Frage kommen: 

- **Espacenet** (Gut für "Stand der Technik"-Recherche)
- **DPMA Register** (Gut für Schutzrecht-Recherche und Patentüberwachungen)
- **Europäisches Patentregister (EPO)** (Gut für europäische Patentrecherche)
- **World Intellectual Property Organization (WIPO)**
- **Octimine** (Gut für Gesamtüberblick EU, US und WIPO)
- **Deutsches Patent- und Markenamt (DPMAregister)**
- **DEPATISnet** (60 Mio. Patentdokumente, jedoch teilweise ohne Übersetzung)
- **Google Advanced Patent Search** (Ergebnisse inkl. juristischer Ereignisse)
