### ISSUE TITLE
Konferenzen recherchieren

### ISSUE THREAD

**Issue by TrisRuhm** [LLM-TTT/project#7]

**Comment by tc020** [comment]
* https://www.atzlive.de/veranstaltungen/ (Fachkonferenzen zu Fahrzeug- und Antriebsentwicklung; mit Filtermöglichkeiten zu Automobil-Themen)
* https://www.kfz-auskunft.de/sportkalender/autoausstellungen.html (Messekalender mit den Terminen für Auto-, Oldtimer- und Nutzfahrzeuge-Ausstellungen)
