### ISSUE TITLE
Schlagwörter recherchieren

### ISSUE THREAD

**Issue by TrisRuhm** [LLM-TTT/project#8]

**Comment by tc020** [comment]
Schlüsselwörter (Keywords):

* Schlüsselwörter sind Wörter oder Ausdrücke, die dazu dienen, den Inhalt eines Dokuments oder einer Webseite zu beschreiben.
* Sie werden oft in Dokumenten oder auf Websites verwendet, um Suchmaschinen und Benutzern bei der Identifizierung und dem Auffinden relevanter Informationen zu helfen.
* Schlüsselwörter sind spezifische Wörter oder Phrasen, die das Thema oder den Inhalt eines Textes am besten repräsentieren.
* In der Suchmaschinenoptimierung (SEO) werden Schlüsselwörter ausgewählt und in den Inhalt einer Webseite integriert, um die Sichtbarkeit in den Suchergebnissen zu verbessern.

Schlagwörter (Tags):

* Schlagwörter sind Bezeichnungen oder Etiketten, die verwendet werden, um Inhalte zu kategorisieren und zu organisieren.
* Sie werden oft in Content-Management-Systemen, sozialen Medien, Blogs und anderen Plattformen verwendet, um Beiträge oder Artikel zu kennzeichnen und in bestimmte Kategorien oder Themenbereiche einzuordnen.
* Schlagwörter dienen dazu, Inhalte für Benutzer leichter auffindbar zu machen, indem sie es ermöglichen, nach bestimmten Themen oder Kategorien zu filtern.
* In vielen Fällen handelt es sich bei Schlagwörtern um Schlüsselwörter oder Schlüsselbegriffe, die den Inhalt eines Beitrags oder Artikels am besten beschreiben.

Der Hauptunterschied besteht darin, dass Schlüsselwörter in erster Linie dazu dienen, den Inhalt zu beschreiben und Suchmaschinen bei der Indexierung und dem Auffinden von Inhalten zu helfen, während Schlagwörter dazu dienen, Inhalte zu organisieren und zu kategorisieren, um Benutzern die Navigation und das Finden von relevanten Informationen zu erleichtern.

**Comment by tc020** [comment]
Schlüsselwörter kann das LLM generieren. Schlagwörter sollten für die korrekte Klassifizierung aus der [openThesaurus API](https://www.openthesaurus.de/about/api) gelesen werden.
