### ISSUE TITLE
Business Model Canvas

### ISSUE THREAD

**Issue by TrisRuhm** [LLM-TTT/project#9]

**Comment by MatthiasMeinke** [comment]
[BMC Auto Branche.pdf](https://github.com/LLM-TTT/project/files/13187732/BMC.Auto.Branche.pdf)
[BMC Patent KI.pdf](https://github.com/LLM-TTT/project/files/13187733/BMC.Patent.KI.pdf)

**Comment by tc020** [comment]
Das BMC für die Autobranche brauchen wir wahrscheinlich nicht. Es geht primär um das Produkt. Für unser Recherche-Tool brauchen wir noch mehr Key propositions. Die da wären:

Wen wollen wir ansprechen? 
- Unternehmen
- Mitarbeiter

Was bieten wir den jeweiligen Customers an?
- Leichterer Einstieg in die Recherche (Mitarbeiter)
- Zeitersparnis (Mitarbeiter & Unternehmen)
- Tiefere Recherchemöglichkeiten (Mitarbeiter)
- Risikominderung durch Verletzung anderer Patente (Unternehmen)
- Wettbewerbsanalyse (Unternehmen)
- Potentielle neue Partnerschaften mit anderen Patenthaltern (Unternehmen)
